name: flutter_boilerplate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Ajax请求
  dio: ^4.0.0
  # 更方便的提示器
  flutter_easyloading: ^3.0.0
  # 图片选择
  image_picker: ^0.8.3+3
  # 图片裁剪
  image_cropper: ^1.4.1
  # 生产者消费者模式的数据服务
  provider: ^6.0.0
  # k-v 数据存储
  shared_preferences: ^2.0.6
  # 下拉刷新上拉加载更多
  flutter_easyrefresh: ^2.2.1
  # 元组
  tuple: ^2.0.0
  # json序列化标记
  json_annotation: ^4.0.0
  # 富文本
  flutter_html: ^2.1.1
  # 图片预览
  photo_view: ^0.12.0
  # 尺寸适配
  # flutter_screenutil: ^5.0.0+2
  # 网络图片缓存
  cached_network_image: ^3.1.0
  # 基于dio的网络请求生成器
  retrofit: ^2.0.1
  # 类似dayjs
  jiffy: ^4.1.0
  # 截屏
  # screenshot: ^1.2.3
  # 保存图片到相册
  image_gallery_saver: '^1.6.9'
  # 异常统计和上报
  flutter_bugly: ^0.3.3
  # 权限管理
  permission_handler: ^8.1.6
  # 应用信息
  package_info_plus: ^1.0.6
  # 应用安装
  install_plugin:
    git:
      url: https://github.com/erguotou520/flutter_install_plugin.git
      ref: master
  # 路径
  path_provider: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  build_runner: ^2.1.1
  json_serializable: ^4.1.4
  retrofit_generator: ^2.0.1
  change_app_package_name: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo.png'